import { latinFoldForSearch } from './latinFold'
import type { LanguageCode } from '../data/words'

export type TokenCloudEntry = {
  token: string
  count: number
  /** 0–1 for font scaling */
  weight: number
}

/** Minimal stopword lists per language (function words only). */
const STOPWORDS: Record<LanguageCode, ReadonlySet<string>> = {
  EN: new Set([
    'a',
    'an',
    'the',
    'and',
    'or',
    'but',
    'if',
    'to',
    'of',
    'in',
    'on',
    'at',
    'for',
    'with',
    'as',
    'by',
    'from',
    'is',
    'are',
    'was',
    'were',
    'be',
    'been',
    'being',
    'have',
    'has',
    'had',
    'do',
    'does',
    'did',
    'will',
    'would',
    'could',
    'should',
    'may',
    'might',
    'must',
    'not',
    'no',
    'so',
    'than',
    'then',
    'too',
    'very',
    'just',
    'this',
    'that',
    'these',
    'those',
    'it',
    'its',
    'he',
    'she',
    'they',
    'them',
    'we',
    'you',
    'i',
    'my',
    'your',
    'his',
    'her',
    'our',
    'their',
    'me',
    'him',
    'us',
  ]),
  DE: new Set([
    'der',
    'die',
    'das',
    'ein',
    'eine',
    'einen',
    'einem',
    'einer',
    'eines',
    'und',
    'oder',
    'aber',
    'wenn',
    'zu',
    'in',
    'an',
    'auf',
    'mit',
    'von',
    'aus',
    'für',
    'ist',
    'sind',
    'war',
    'waren',
    'hat',
    'haben',
    'hatte',
    'hatten',
    'wird',
    'werden',
    'nicht',
    'auch',
    'nur',
    'sehr',
    'ich',
    'du',
    'er',
    'sie',
    'es',
    'wir',
    'ihr',
    'mich',
    'dich',
    'mir',
    'dir',
    'ihm',
    'ihr',
    'uns',
    'euch',
    'mein',
    'dein',
    'sein',
    'ihr',
    'unser',
    'euer',
  ]),
  PT: new Set([
    'o',
    'a',
    'os',
    'as',
    'um',
    'uma',
    'uns',
    'umas',
    'de',
    'do',
    'da',
    'dos',
    'das',
    'em',
    'no',
    'na',
    'nos',
    'nas',
    'por',
    'para',
    'com',
    'e',
    'ou',
    'mas',
    'se',
    'que',
    'é',
    'são',
    'foi',
    'foram',
    'tem',
    'têm',
    'não',
    'muito',
    'eu',
    'tu',
    'ele',
    'ela',
    'nós',
    'vocês',
    'eles',
    'elas',
    'me',
    'te',
    'lhe',
    'nos',
    'vos',
    'meu',
    'minha',
    'seu',
    'sua',
  ]),
  ES: new Set([
    'el',
    'la',
    'los',
    'las',
    'un',
    'una',
    'unos',
    'unas',
    'de',
    'del',
    'y',
    'o',
    'pero',
    'si',
    'en',
    'por',
    'para',
    'con',
    'es',
    'son',
    'era',
    'eran',
    'fue',
    'fueron',
    'tiene',
    'tienen',
    'no',
    'muy',
    'yo',
    'tú',
    'él',
    'ella',
    'nosotros',
    'vosotros',
    'ellos',
    'ellas',
    'me',
    'te',
    'le',
    'nos',
    'os',
    'mi',
    'tu',
    'su',
  ]),
  FR: new Set([
    'le',
    'la',
    'les',
    'un',
    'une',
    'des',
    'de',
    'du',
    'et',
    'ou',
    'mais',
    'si',
    'dans',
    'sur',
    'pour',
    'avec',
    'par',
    'est',
    'sont',
    'était',
    'étaient',
    'a',
    'ont',
    'avait',
    'avaient',
    'ne',
    'pas',
    'plus',
    'très',
    'je',
    'tu',
    'il',
    'elle',
    'on',
    'nous',
    'vous',
    'ils',
    'elles',
    'me',
    'te',
    'se',
    'mon',
    'ton',
    'son',
    'notre',
    'votre',
    'leur',
  ]),
  IT: new Set([
    'il',
    'lo',
    'la',
    'i',
    'gli',
    'le',
    'un',
    'uno',
    'una',
    'di',
    'del',
    'della',
    'e',
    'o',
    'ma',
    'se',
    'in',
    'con',
    'per',
    'su',
    'da',
    'è',
    'sono',
    'era',
    'erano',
    'ha',
    'hanno',
    'non',
    'molto',
    'io',
    'tu',
    'lui',
    'lei',
    'noi',
    'voi',
    'loro',
    'mi',
    'ti',
    'ci',
    'vi',
    'mio',
    'mia',
    'tuo',
    'tua',
    'suo',
    'sua',
  ]),
}

function tokenizeSentences(sentences: readonly string[]): string[] {
  const tokens: string[] = []
  for (const line of sentences) {
    const matches = line.toLowerCase().match(/\p{L}+/gu)
    if (!matches) continue
    for (const m of matches) {
      const folded = latinFoldForSearch(m)
      if (folded.length > 1) tokens.push(folded)
    }
  }
  return tokens
}

function exclusionSet(exclude: readonly string[] | undefined): Set<string> {
  const s = new Set<string>()
  if (!exclude) return s
  for (const x of exclude) {
    const f = latinFoldForSearch(x).trim()
    if (f) s.add(f)
  }
  return s
}

/**
 * Count tokens across sentences, drop stopwords and excluded lemmas, return sorted by count desc.
 */
export function buildSentenceTokenCloud(
  sentences: readonly string[],
  lang: LanguageCode,
  options?: { excludeLemmaForms?: readonly string[] },
): TokenCloudEntry[] {
  const stop = STOPWORDS[lang]
  const banned = exclusionSet(options?.excludeLemmaForms)
  const counts = new Map<string, number>()
  for (const t of tokenizeSentences(sentences)) {
    if (stop.has(t)) continue
    if (banned.has(t)) continue
    counts.set(t, (counts.get(t) ?? 0) + 1)
  }
  const entries = [...counts.entries()].map(([token, count]) => ({ token, count }))
  entries.sort((a, b) => b.count - a.count || a.token.localeCompare(b.token))
  const max = entries[0]?.count ?? 1
  return entries.slice(0, 24).map((e) => ({
    ...e,
    weight: e.count / max,
  }))
}
